routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

// Route::get('/', function () {
// 	return view('login');
// })

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::middleware(['auth'])->group(function () {
Route::get('admins', function () {
        return view('admin.dashboard');
    })->name('admin.adashboard');

Route::prefix('admins')->group(function () {
    Route::resource('company', 'CompanyController');
	});

 Route::prefix('admins')->group(function () {
    Route::resource('employee', 'EmployeeController');
	});

});

app/Company.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Company extends Model
{
    protected $fillable=['name','email','image'];
}

app/Http/Controllers/CompanyController.php
<?php

namespace App\Http\Controllers;

use App\Company;
use File;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Validator;

class CompanyController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $search = $request->search;
        $query = Company::query();
        if($search){
            $query =$query->Where('name','like','%'.$search.'%')->orWhere('email','like','%'.$search.'%');
        }
        $company = $query->paginate(10);
        return view('admin.company.index',compact('company'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.company.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
         $validator = Validator::make($request->all(), [
            'name' => 'required',
            
            
        ]);

        if ($validator->fails()) {
            return redirect(route('company.create'))
                ->withErrors($validator)
                ->withInput();
        }

        $company=Company::create($request->all());
         $file = $request->file('image');
        if (!empty($file)) {
            $destinationPath = 'uploads/company/';
            $filename = $file->getClientOriginalName();
            $file->move($destinationPath, $filename);
            $company->image = $filename;
            $company->save();
        }
        return redirect(route('company.create'));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Company  $company
     * @return \Illuminate\Http\Response
     */
    public function show(Company $company)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Company  $company
     * @return \Illuminate\Http\Response
     */
    public function edit(Company $company)
    {
        return view('admin.company.edit',compact('company'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Company  $company
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Company $company)
    {
          $validator = Validator::make($request->all(), [
            'name' => 'required',

        ]);

        if ($validator->fails()) {
            return redirect()->back()->withErrors($validator)->withInput()
                ->withErrors($validator)
                ->withInput();
        }


        $company->name=$request->name;
        $company->email=$request->email;
        

        $file = $request->file('image');
        if (!empty($file)) {
            $destinationPath = 'uploads/company/';
            File::delete($destinationPath.$company->image);//delete current image from storage
            $filename = $file->getClientOriginalName();
            $file->move($destinationPath, $filename);
            $company->image = $filename;
        }


        $company->save();
        return redirect(route('company.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Company  $company
     * @return \Illuminate\Http\Response
     */
    public function destroy(Company $company)
    {
        //
    }
}

resources/views/admin/company/create.blade.php
@extends('layouts.backend.master')
@section('content')


<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        Company Form 
        
      </h1>
      <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
        <li><a href="#">Company</a></li>
        <li class="active">Create</li>
      </ol>
    </section>
 <!-- Main content -->
    <section class="content">
      <div class="row">
        <!-- left column -->
        <div class="col-md-12">
          <!-- general form elements -->
          <div class="box box-primary">
            <div class="box-header with-border">
              <h3 class="box-title">Company Details</h3>
            </div>
            <!-- /.box-header -->
            <!-- form start -->
            <form role="form" action="{{ action('CompanyController@store') }}" method="post" enctype="multipart/form-data">
              @csrf
              <div class="box-body">
                <div class="form-group">
                  <label for="exampleInputEmail1">Company Name</label>
                  <input type="text" class="form-control" name='name' id="exampleInputEmail1" placeholder="Enter name" required="required">
                </div>
                <div class="form-group">
                  <label for="exampleInputEmail1">Company Email</label>
                  <input type="text" class="form-control" name='email' id="exampleInputEmail1" placeholder="Enter email">
                </div>
              </div>
              <div class="form-group">
                  <label for="exampleInputFile">File input</label>
                  <input type="file" id="exampleInputFile" name="image">

                  <p class="help-block">Company Logo </p>
                </div>
              <!-- /.box-body -->

              <div class="box-footer">
                <button type="submit" class="btn btn-primary">Submit</button>
              </div>
            </form>
          </div>
          <!-- /.box -->
      </div>
  </div>
</section>
</div>

@endsection

resources/views/admin/company/edit.blade.php
@extends('layouts.backend.master')
@section('content')


<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        Company Edit Form 
        
      </h1>
      <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
        <li><a href="#">Company</a></li>
        <li class="active">Edit</li>
      </ol>
    </section>
 <!-- Main content -->
    <section class="content">
      <div class="row">
        <!-- left column -->
        <div class="col-md-12">
          <!-- general form elements -->
          <div class="box box-primary">
            <div class="box-header with-border">
              <h3 class="box-title">Details</h3>
            </div>
            <!-- /.box-header -->
            <!-- form start -->
            <form role="form" action="{{ route('company.update',$company->id) }}" method="post" enctype="multipart/form-data">
              @csrf
               @method('PUT')
              <div class="box-body">
                <div class="form-group">
                  <label for="exampleInputEmail1">Company Name</label>
                  <input type="text" class="form-control" value="{{$company->name}}" name='name' id="exampleInputEmail1" placeholder="Enter name" required="required">
                </div>
                <div class="form-group">
                  <label for="exampleInputEmail1">Company Email</label>
                  <input type="text" class="form-control" value="{{$company->email}}" name='email' id="exampleInputEmail1" placeholder="Enter email" required="required">
                </div>
              </div>
              @if (!empty($company->image))
              <div class="form-group col-12">
                  <img  id="upload-image" width="100px" src="{{asset('uploads/company/'.$company->image)}}" alt="" />
              </div>
              @endif
              <div class="form-group">
                  <label for="exampleInputFile">File input</label>
                  <input type="file" id="exampleInputFile" name="image">

                  <p class="help-block">Company Logo </p>
                </div>
              <!-- /.box-body -->

              <div class="box-footer">
                <button type="submit" class="btn btn-primary">Update</button>
              </div>
            </form>
          </div>
          <!-- /.box -->
      </div>
  </div>
</section>
</div>

@endsection

resources/views/admin/company/index.blade.php
 @extends('layouts.backend.master')
@section('content')
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/limonte-sweetalert2/7.18.0/sweetalert2.min.css">
    <meta name="csrf-token" content="{{ csrf_token() }}">

 <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        Companies
        
      </h1>
      <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
        <li><a href="#">Company</a></li>
        <li class="active">View</li>
      </ol>
    </section>

    <section class="content">
      <div class="row">
        <div class="col-xs-12">
           
          <div class="box">
            <div class="box-header">
              <h3 class="box-title">Companies Details</h3>
            </div>
            <div class="float-right">
              <div class="container">
                  <div class="col-xs-4">
                <form action="{{ action('CompanyController@index') }}" method="get" role="search">
                    {{ csrf_field() }}
                    <div class="input-group">
                        <input type="text" class="form-control" name="q"
                            placeholder="Search users"> <span class="input-group-btn">
                            <button type="submit" class="btn btn-default">
                                <span class="glyphicon glyphicon-search"></span>
                            </button>
                        </span>
                    </div>
                </form>
              </div>
            </div>
                                </div>
            <!-- /.box-header -->
            <div class="box-body">
              <table id="example1" class="table table-bordered table-striped">
                <thead>
                <tr>
                  <th>#</th>
                  <th>Name</th>
                  <th>Email Address</th>
                  <th>Image</th>
                  <th>Option</th>
                </tr>
                </thead>
                <tbody>
                   @foreach ($company as $key => $data)
                <tr>
                  <td>{{++$key}}</td>
                  <td>{{$data->name}}</td>
                  <td>{{$data->email}}</td>
                   <td><img width="100px" src="{{asset('uploads/company/'.$data->image)}}" alt="" /></td>
                   <td><a href="{{route('company.edit',[$data->id])}}" class="btn btn-action btn-primary">Edit</a>
                  <a href="{{route('company.destroy',$data->id)}}" data-method="delete" class="btn btn-action btn-danger jquery-post">Delete</a></td>
                </tr>
                @endforeach
                </tbody>
              </table>
              {{ $company->links() }}
            </div>
            <!-- /.box-body -->
          </div>
          <!-- /.box -->
        </div>
        <!-- /.col -->
      </div>
      <!-- /.row -->
    </section>
    <!-- /.content -->
  </div>
 
  @endsection


  @section('additional_scripts')

    <script src="https://cdnjs.cloudflare.com/ajax/libs/limonte-sweetalert2/7.18.0/sweetalert2.min.js"></script>
    <script>
        $(document).on('click', 'a.jquery-post', function(e) {
            $.ajaxSetup({
                headers: {
                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                }
            });
            e.preventDefault(); // does not go through with the link.
            var $this = $(this);
            Swal.fire({
                title: 'Are you sure?',
                text: "You won't be able to revert this!",
                type: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Yes, delete it!'
            }).then((result) => {
                if (result.value){
                    $.post({
                         type: 'DELETE',
                        url: $this.attr('href')
                    }).done(function (data) {
                        Swal.fire(
                            'Deleted!',
                            'Your file has been deleted.',
                            'success'
                        )
                        window.location.reload();
                    });
                }
            });
        });
    </script>
    @endsection