routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

// Route::get('/', function () {
// 	return view('login');
// })

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::middleware(['auth'])->group(function () {
Route::get('admins', function () {
        return view('admin.dashboard');
    })->name('admin.adashboard');

Route::prefix('admins')->group(function () {
    Route::resource('company', 'CompanyController');
	});

 Route::prefix('admins')->group(function () {
    Route::resource('employee', 'EmployeeController');
	});

});

app/Employee.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Employee extends Model
{
    protected $fillable = ['fname','lname','company_id','personal_email','phone_number'];
}

app/Http/Controllers/EmployeeController.php
<?php

namespace App\Http\Controllers;

use App\Employee;
use Illuminate\Http\Request;
use App\Company;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Validator;


class EmployeeController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
         $company = Company::pluck('name', 'id');

         
        $search = $request->search;
        $query = Employee::query();
        if($search){
            $query =$query->Where('fname','like','%'.$search.'%')->orWhere('lname','like','%'.$search.'%');
        }
        $employee = $query->paginate(10);
        return view('admin.employee.index',compact('employee','company'));

        //  $employee = \DB::table('companies')
        // ->join('employees', 'company_id', '=', 'companies.id')
        // ->where('companies.id')
        // ->paginate(10);
       
        
        // return view('admin.employee.index',compact('employee'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
         $company = Company::pluck('name', 'id');

         $selectedID = 2;
            // return $posts;
        return view('admin.employee.create', compact('selectedID', 'company'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $employee = Employee::create($request->all());
        return redirect(route('employee.create'));

    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Employee  $employee
     * @return \Illuminate\Http\Response
     */
    public function show(Employee $employee)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Employee  $employee
     * @return \Illuminate\Http\Response
     */
    public function edit(Employee $employee)
    {
         $company = Company::pluck('name', 'id');

         $selectedID = 2;
        return view('admin.employee.edit',compact('employee','company','selectedID'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Employee  $employee
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Employee $employee)
    {
        $validator = Validator::make($request->all(), [
            'fname' => 'required',
            'lname' => 'required',
            'company_id' => 'required',
            'personal_email' => 'required',
            'phone_number' => 'required',

        ]);

        if ($validator->fails()) {
            return redirect()->back()->withErrors($validator)->withInput()
                ->withErrors($validator)
                ->withInput();
        }


        $employee->fname=$request->fname;
        $employee->lname=$request->lname;
        $employee->company_id=$request->company_id;
        $employee->personal_email=$request->personal_email;
        $employee->phone_number=$request->phone_number;
    


        $employee->save();
        return redirect(route('employee.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Employee  $employee
     * @return \Illuminate\Http\Response
     */
    public function destroy(Employee $employee)
    {
         $employee = Employee::findOrFail($id);
    $employee->delete();

    return redirect(route('employee.index'));
    }
}

resources/views/admin/employee/create.blade.php
@extends('layouts.backend.master')
@section('content')


<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        Employee Form 
        
      </h1>
      <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
        <li><a href="#">Employee</a></li>
        <li class="active">Create</li>
      </ol>
    </section>
 <!-- Main content -->
    <section class="content">
      <div class="row">
        <!-- left column -->
        <div class="col-md-12">
          <!-- general form elements -->
          <div class="box box-primary">
            <div class="box-header with-border">
              <h3 class="box-title">Employee Details</h3>
            </div>
            <!-- /.box-header -->
            <!-- form start -->
            <form role="form" action="{{ action('EmployeeController@store') }}" method="post" enctype="multipart/form-data">
              @csrf
              <div class="box-body">
                <div class="form-group">
                  <label for="exampleInputEmail1">Employee First Name</label>
                  <input type="text" class="form-control" name='fname' id="exampleInputEmail1" placeholder="Enter name" required="required">
                </div>
                <div class="form-group">
                  <label for="exampleInputEmail1">Employee Last Name</label>
                  <input type="text" class="form-control" name='lname' id="exampleInputEmail1" placeholder="Enter name" required="required">
                </div>
                <div class="form-group">
                  <label>Select Company</label>
                  <select class="form-control" name="company_id">
                    <option>Select Company</option>
                    @foreach ($company as $key => $value)
                    <option value="{{ $key }}" {{ ( $key == $selectedID) ? 'selected' : '' }}> 
                      {{$value}}
                      </option>
                     @endforeach   
                  </select>
                </div>
                <div class="form-group">
                  <label for="exampleInputEmail1">Employee Personal Email</label>
                  <input type="text" class="form-control" name='personal_email' id="exampleInputEmail1" placeholder="Enter email">
                </div>
                 <div class="form-group">
                  <label for="exampleInputEmail1">Employee Phone Number</label>
                  <input type="text" class="form-control" name='phone_number' id="exampleInputEmail1" placeholder="Enter email">
                </div>
              </div>
              
              <!-- /.box-body -->

              <div class="box-footer">
                <button type="submit" class="btn btn-primary">Submit</button>
              </div>
            </form>
          </div>
          <!-- /.box -->
      </div>
  </div>
</section>
</div>

@endsection

resources/views/admin/employee/edit.blade.php
@extends('layouts.backend.master')
@section('content')


<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        Employee Edit Form 
        
      </h1>
      <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
        <li><a href="#">Employee</a></li>
        <li class="active">Edit</li>
      </ol>
    </section>
 <!-- Main content -->
    <section class="content">
      <div class="row">
        <!-- left column -->
        <div class="col-md-12">
          <!-- general form elements -->
          <div class="box box-primary">
            <div class="box-header with-border">
              <h3 class="box-title">Details</h3>
            </div>
            <!-- /.box-header -->
            <!-- form start -->
            <form role="form" action="{{ route('employee.update',$employee->id) }}" method="post" enctype="multipart/form-data">
              @csrf
               @method('PUT')
              <div class="box-body">
                <div class="form-group">
                  <label for="exampleInputEmail1">Employee First Name</label>
                  <input type="text" class="form-control" value="{{$employee->fname}}" name='fname' id="exampleInputEmail1" placeholder="Enter name" required="required">
                </div>
                <div class="form-group">
                  <label for="exampleInputEmail1">Employee Last Name</label>
                  <input type="text" class="form-control" value="{{$employee->lname}}" name='lname' id="exampleInputEmail1" placeholder="Enter name" required="required">
                </div>
                 <div class="form-group">
                  <label>Select Company</label>
                  <select class="form-control" name="company_id">
                    <option>Select Company</option>
                    @foreach ($company as $key => $value)
                    <option value="{{ $key }}" {{ ( $key == $selectedID) ? 'selected' : '' }}> 

                      {{$value}}
                      </option>
                     @endforeach   
                  </select>
                </div>

                <div class="form-group">
                  <label for="exampleInputEmail1">Employee Email</label>
                  <input type="text" class="form-control" value="{{$employee->personal_email}}" name='personal_email' id="exampleInputEmail1" placeholder="Enter email" required="required">
                </div>
                <div class="form-group">
                  <label for="exampleInputEmail1">Employee Phone number</label>
                  <input type="text" class="form-control" value="{{$employee->phone_number}}" name='phone_number' id="exampleInputEmail1" placeholder="Enter number" required="required">
                </div>
              </div>
             
              
              <!-- /.box-body -->

              <div class="box-footer">
                <button type="submit" class="btn btn-primary">Update</button>
              </div>
            </form>
          </div>
          <!-- /.box -->
      </div>
  </div>
</section>
</div>

@endsection

resources/views/admin/employee/index.blade.php
 @extends('layouts.backend.master')
@section('content')
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/limonte-sweetalert2/7.18.0/sweetalert2.min.css">
    <meta name="csrf-token" content="{{ csrf_token() }}">

 <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        Employees
        
      </h1>
      <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
        <li><a href="#">Employees</a></li>
        <li class="active">View</li>
      </ol>
    </section>

    <section class="content">
      <div class="row">
        <div class="col-xs-12">
           
          <div class="box">
            <div class="box-header">
              <h3 class="box-title">Employees Details</h3>
            </div>
            <div class="float-right">
              <div class="container">
                  <div class="col-xs-4">
                <form action="{{ action('EmployeeController@index') }}" method="get" role="search">
                    {{ csrf_field() }}
                    <div class="input-group">
                        <input type="text" class="form-control" name="q"
                            placeholder="Search users"> <span class="input-group-btn">
                            <button type="submit" class="btn btn-default">
                                <span class="glyphicon glyphicon-search"></span>
                            </button>
                        </span>
                    </div>
                </form>
              </div>
            </div>
                                </div>
            <!-- /.box-header -->
            <div class="box-body">
              <table id="example1" class="table table-bordered table-striped">
                <thead>
                <tr>
                  <th>#</th>
                  <th>First Name</th>
                  <th>Last Name</th>
                  <th>Email Address</th>
                  <th>Phone Number</th>
                  <th>Option</th>
                </tr>
                </thead>
                <tbody>
                   @foreach ($employee as $key => $data)
                <tr>
                  <td>{{++$key}}</td>
                  <td>{{$data->fname}}</td>
                  <td>{{$data->lname}}</td>
                  @foreach ($company as $cc => $com)
                  @if($data->company_id == $cc){
                    <td>{{$com}}</td> 
                  }@endif
                  @endforeach
                  <td>{{$data->personal_email}}</td>
                  <td>{{$data->phone_number}}</td>
                   
                   <td><a href="{{route('employee.edit',[$data->id])}}" class="btn btn-action btn-primary">Edit</a>
                  <a href="{{route('employee.destroy',$data->id)}}" data-method="delete" class="btn btn-action btn-danger ">Delete</a></td>
                </tr>
                @endforeach
                </tbody>
              </table>
              {{ $employee->links() }}
            </div>
            <!-- /.box-body -->
          </div>
          <!-- /.box -->
        </div>
        <!-- /.col -->
      </div>
      <!-- /.row -->
    </section>
    <!-- /.content -->
  </div>
 
  @endsection


  @section('additional_scripts')

    <script src="https://cdnjs.cloudflare.com/ajax/libs/limonte-sweetalert2/7.18.0/sweetalert2.min.js"></script>
    <script>
        $(document).on('click', 'a.jquery-post', function(e) {
            $.ajaxSetup({
                headers: {
                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                }
            });
            e.preventDefault(); // does not go through with the link.
            var $this = $(this);
            Swal.fire({
                title: 'Are you sure?',
                text: "You won't be able to revert this!",
                type: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Yes, delete it!'
            }).then((result) => {
                if (result.value){
                    $.post({
                         type: 'DELETE',
                        url: $this.attr('href')
                    }).done(function (data) {
                        Swal.fire(
                            'Deleted!',
                            'Your file has been deleted.',
                            'success'
                        )
                        window.location.reload();
                    });
                }
            });
        });
    </script>
    @endsection